Feature/adapt to rollups node 1.3.0
cartesi/helm-charts pull request #77
Opened 2023-12-19 16:59 UTC by endersonmaia

This PR will adapt to rollups-node:1.3.0.

As steps to simplify our chart code, it will:

- [ ] Remove option to install a localnode
- [ ] Remove the option to install a Redis instance
- [ ] Remove the option to install a PostgreSQL
- [ ] Remove the option to pass Redis or PostgreSQL configuration via `.Values`

2024-01-31 11:10 UTC, oap75 commented
> * Remove option to install a localnode
> * [x]  Remove the option to install a Redis instance
> * [x]  Remove the option to install a PostgreSQL
> *

Why do we need to remove these options ? Don't we need to test the helm chart locally with localnode anymore ?

2024-01-31 11:37 UTC, endersonmaia commented
> Why do we need to remove these options ? Don't we need to test the helm chart locally with localnode anymore ?

To make it simple, the chart will only be responsible for the rollups-node, everything else should be out of scope.

All the rollups-node dependencies are documented on the cartesi/rollups-node documentation, we could link to it docs.

2024-02-02 16:22 UTC, oap75 requested changes

2024-02-02 16:22 UTC, oap75 commented on charts/rollups-node/templates/NOTES.txt
>    export CONTAINER_PORT=$(kubectl get pod --namespace {{ .Release.Namespace }} $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
We do not have `containerPort` in deployment section.

2024-02-15 13:53 UTC, oap75 requested changes
Need rebase

2024-02-15 15:28 UTC, oap75 approved these changes
LGTM 🚀

2024-02-15 15:49 UTC, merged